global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:4001']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'shipment-service'
    static_configs:
      - targets: ['host.docker.internal:5000']
